name: Dependency Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 4'
permissions: read-all

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 23

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    if: >
      github.actor != 'dependabot[bot]'
      && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptium.net:443
            api.github.com:443
            caffeine.gradle-enterprise.cloud:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            github.com:443
            jcenter.bintray.com:443
            jeremylong.github.io:443
            nvd.nist.gov:443
            objects.githubusercontent.com:443
            ossindex.sonatype.org:443
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            raw.githubusercontent.com:443
            services.gradle.org:443
            www.cisa.gov:443
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run dependency-check
        uses: ./.github/actions/run-gradle
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: dependencyCheckAggregate --no-configuration-cache
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: build/reports/dependency-check-report.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@df409f7d9260372bd5f19e5b04e83cb3c43714ae # v3.27.9
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          sarif_file: build/reports/dependency-check-report.sarif
